version: '3'
services:

  #PHP Service
  app:
    image: your-docker-registry/php-app:tag
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.env:/var/www/.env
    networks:
      - app-network
    ports:
      - "9000:9000"

#Docker Networks
networks:
  app-network:
    driver: bridge